### ISSUE TITLE
222Rn half-life value is off by a factor of 24 in data/beta_decays.dat

### ISSUE THREAD

**Issue by ViacheslavLi** [AIT-WATCHMAN/rat-pac#58]
In rat-pac/data/beta_decays.dat, the value for the half life of Rn-222 is listed as 1.376e+04 (in seconds) which corresponds to 3.82 hours.
However, the actual half life of the Rn-222 is 3.82 days (not hours!)
https://www-nds.iaea.org/relnsd/vcharthtml/VChartHTML.html#dcy1

3.8235 days = 3.30350e+05 seconds

**Comment by MorganAskins** [comment]
Nice catch, I would recommend that as part of the fix to this issue would be to double check the others as well. Where these values all put in by hand or via a script?

Example: Uranium series is missing 234mPa state and has 234Pa in its place (and in the wrong spot).

**Comment by ViacheslavLi** [comment]
I checked U-238 chain. The rest of the values look okay.
Yes, 234mPa state is missing, but how to add it?
What do you mean by "234Pa in its place (and in the wrong spot)"?
