### ISSUE TITLE
GeoBuilder error: volume cables has no mother

### ISSUE THREAD

**Issue by ViacheslavLi** [AIT-WATCHMAN/rat-pac#68]
After running:
$ watchmakers -C 25pct -j -m
$ ./jobs_veto_coverage_0.002_vetoThickR_3080.000000_vetoThickZ_3080.000000/25pct/WaterVolume/promptDelayedPair/pn_ibd/job00000000.sh

**Comment by MarcFBergevin** [comment]
Cables have been removed and this is now resolved.
