### ISSUE TITLE
Thermal neutron simulation sometimes prduces two subevents in an event

### ISSUE THREAD

**Issue by feliciasutanto** [AIT-WATCHMAN/rat-pac#97]
Hello WATCHMAN people!

Kris Ogren and I just recently downloaded a new copy of ratpac (May18, 2020) and we ran a thermal neutron simulation in the water volume. We notice that sometimes one event produces two subevents. This is not expected at all from a thermal neutron simulation..... Also, Marc notices that the PMT timing looks a bit weird (sometimes you see negative time stamp).

This is how the macro looks like:

**/rat/db/set DETECTOR experiment "Watchman"
/rat/db/set DETECTOR detector_factory "Watchman"
/rat/db/set WATCHMAN_PARAMS photocathode_coverage 2.00000e-01
/rat/db/set WATCHMAN_PARAMS veto_coverage 2.00000e-02
/rat/db/set GEO[shield] veto_thickness_r 3.30000e+03
/rat/db/set GEO[shield] veto_thickness_z 3.30000e+03
/run/initialize
/rat/proc lesssimpledaq 
/rat/proc count 
/rat/procset update 10
/rat/proclast outroot 
/rat/procset file "out.root"
/generator/add combo gun:fill:poisson 
/generator/pos/set detector+ 
/generator/vtx/set neutron 0 0 0 0.000000025 
/run/beamOn 1000**

and this is an example of two subevents in one event:

**NUM OF SUBEVENTS: 2
EV PMT Cnt:    73661 and Cluster Time:      0.000 
EV  0 PMT  0: (pmtID, charge,time) (3629,     0.90,     0.00)
EV  0 PMT  1: (pmtID, charge,time) (3659,     1.68,    37.86)
EV  0 PMT  2: (pmtID, charge,time) (3373,     0.98,    60.40)
EV  0 PMT  3: (pmtID, charge,time) (3627,     0.65,    88.53)
EV  0 PMT  4: (pmtID, charge,time) (3426,     1.17,   123.75)
EV  0 PMT  5: (pmtID, charge,time) (3523,     1.45,   155.54)
EV  0 PMT  6: (pmtID, charge,time) (3609,     0.96,   159.14)
EV  0 PMT  7: (pmtID, charge,time) (3365,     1.36,   191.37)
EV  0 PMT  8: (pmtID, charge,time) (3585,     1.08,   221.76)
EV  0 PMT  9: (pmtID, charge,time) (3379,     1.23,   298.05)
EV  0 PMT 10: (pmtID, charge,time) (3559,     1.61,   330.46)
EV PMT Cnt:      867 and Cluster Time:     13.078 
EV  1 PMT  0: (pmtID, charge,time) (3490,     1.29,  -264.48)
EV  1 PMT  1: (pmtID, charge,time) (3629,     0.84,     0.00)**

**Comment by feliciasutanto** [comment]
More info about the issue:

The veto PMTs are very very active...
<img width="555" alt="Screen Shot 2020-05-19 at 10 48 29 AM" src="https://user-images.githubusercontent.com/19483957/82361116-46920780-99bf-11ea-845c-95b4574765c7.png">

**Comment by akindele** [comment]
Oh this may be due to the tyvek implementation.

**Comment by MarcFBergevin** [comment]
Oh, yes, the tyvek might be the cause of this. Also, the PMT id's in the printout is all  veto PMTs I believe.

**Comment by MarcFBergevin** [comment]
We might want to change the default rat-pac geometry to have a inner and outer volume and simulate those two contribution independendly.

**Comment by ekneale** [comment]
There are two issues here. I ran 1000 neutron events and 1142 events triggered. Of these 313 were re-triggers and all of them were in the veto PMTs.

As for the negative PMT hit times, in LessSimpleDAQProc the clusterTime (trigger time) of a second sub event is set as the earliest hit time beyond 800ns from the first clusterTime (first PMT hit overall). Then at line 133 the PMT hits are grouped into one sub event if they are within 400ns either side of the clusterTime. So hits in the tails of earlier events are being included in the following sub events if they are between 400ns and 800ns after the trigger time of the first sub event. Then in line 166 the hit time is saved as PMT hit time (from start of MC) - clusterTime. The hits from the previous sub event occurred before the clusterTime assigned, hence the negative times. 

For these events, I initially changed the window at line 133 to [-200,600] and then to [-100,700]. The latter largely removed the negative pmt hit times (7 sub events out of the 313 re-triggers had negative hit times).

**Comment by feliciasutanto** [comment]
Solution is explained in pull request #102. Maybe we can close this ticket?
